name: Deploy HTML/CSS Website to Hostinger

# Trigger the workflow on every push to the main branch
on:
  push:
    branches:
      - main # Replace 'main' with your branch name if it's different

jobs:
  deploy:
    runs-on: ubuntu-latest # The operating system for the workflow

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Deploy files to Hostinger via FTP
      - name: Deploy to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }} # Hostinger FTP server
          username: ${{ secrets.FTP_USERNAME }} # FTP username
          password: ${{ secrets.FTP_PASSWORD }} # FTP password
          local-dir: ./ # Directory containing your HTML/CSS files
          server-dir: /public_html/ # The Hostinger web root directory
